services:
    ReCaptcha\ReCaptcha:
        arguments:
            $secret: '%env(GOOGLE_RECAPTCHA_PRIVATE_KEY)%'
            $requestMethod: '@ReCaptcha\RequestMethod'

    # Curl is set here as default transport to communicate with Google servers.
    # If you do not have php-curl extension, you can change for a socket or a plain POST request.
    # Check out the repository for all other request methods:
    # https://github.com/google/recaptcha/tree/master/src/ReCaptcha/RequestMethod
    ReCaptcha\RequestMethod: '@ReCaptcha\RequestMethod\CurlPost'
    ReCaptcha\RequestMethod\CurlPost: null
    ReCaptcha\RequestMethod\Curl: null
